cmake/FindCatch2.cmake, tests/CMakeLists.txt
`find_package` is the canonical way to express dependencies in CMake and conveniently provides a mechanism for override the default package search logic by simply providing your own Find<Package>.cmake file. This means when it comes time to use a system install of Catch2, we can just delete this custom module.
This also has the benefit of providing a neatly contained CMake module that others can paste into their projects if need be to avoid them having to write all this code themselves.
=> Find Catch2 via find_package

include/rsl/queue.hpp, tests/CMakeLists.txt, tests/queue.cpp
Implements a thread-safe queue. Particularly useful when multiple threads need to read from and/or write to a queue.
=> Add `rsl::Queue`

include/rsl/monad.hpp, package.xml, tests/CMakeLists.txt, tests/monad.cpp
Signed-off-by: Tyler Weaver <tyler@picknik.ai>
This includes tests for operator| used to monadic bind with expected types a test to verify this does not conflict with the operator| from range-v3.
=> operator| for plain old values

.github/workflows/docs.yaml, CMakeLists.txt, docs/CMakeLists.txt, include/rsl/monad.hpp, include/rsl/no_discard.hpp, include/rsl/overload.hpp, include/rsl/queue.hpp, include/rsl/random.hpp, include/rsl/try.hpp, package.xml
CI fails if we require that Doxygen is found so I'm leaving that dependency as optional. Along the way I also found a few bugs and documentation deficiencies that I fixed. Now every API has Doxygen support.
Read more about `doxygen_add_docs` [here](https://cmake.org/cmake/help/latest/module/FindDoxygen.html#command:doxygen_add_docs).
See [Halide](https://github.com/halide/Halide/blob/master/doc/CMakeLists.txt) for an example of how this is being used in practice.
=> Add build system support for generating documentation

cmake/FindCatch2.cmake, include/rsl/monad.hpp, include/rsl/no_discard.hpp, tests/overload.cpp, tests/random.cpp
I ran clang-tidy locally and found a number of things worth cleaning up.
=> Address clang-tidy findings

CMakeLists.txt, include/rsl/static_string.hpp, include/rsl/static_vector.hpp, package.xml, tests/CMakeLists.txt, tests/static_string.cpp, tests/static_vector.cpp
- Link rclcpp and rcb_span
- Fixed size array and string
Migrated from https://github.com/PickNikRobotics/generate_parameter_library/blob/main/parameter_traits/include/parameter_traits/fixed_size_types.hpp
=> Add `rsl::StaticVector` and `rsl::StaticString`

CMakePresets.json
There is no C code in RSL so we don't need to specify these C compiler settings.
=> Remove C compiler settings

include/rsl/static_string.hpp, include/rsl/static_vector.hpp, tests/static_string.cpp, tests/static_vector.cpp
We overlooked a few things. clang-tidy caught most of these things so that puts more pressure on us getting that integration working soon before we let more little issues slip through.
=> Clean up static containers implementation

include/rsl/random.hpp, include/rsl/static_string.hpp, include/rsl/static_vector.hpp
I skipped rsl::rng since you can call that function and get side effects so it's not unreasonable to omit [[nodiscard]].
=> Use more `[[nodiscard]]`

CMakeLists.txt
RSL v0.1.1 was shipped in ros-humble-rsl as a static library without position independent code enabled which caused issues with downstream shared libraries that linked to it. This works around that issue while we expore more permanent fixes
=> Always use position independent code

.clang-tidy, .github/workflows/ci.yaml, CMakeLists.txt, include/rsl/static_string.hpp, include/rsl/static_vector.hpp, package.xml, tests/monad.cpp, tests/overload.cpp, tests/queue.cpp
I had to explicitly disable compiler extensions because that forces CMake to emit the `-std=` flag which clang-tidy needs to know what version of C++ GCC is using. Otherwise clang-tidy can't know what C++ version is being used since it doesn't understand how to get the default language standard for GCC. If clang-tidy doesn't know what C++ version is being used then it emits false warnings about missing headers and other nonsense like that. Hopefully I can find a better way to work around this but for now it's a hack we need.
Closes #49
=> Add clang-tidy integration

CMakeLists.txt
It is a standard in Debian to package libraries as shared libraries and
only optionally provide a static library.
Reference:
https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#static-libraries
The reasons for building as a SHARED library by default are:
- Shared libraries can be updated without rebuilding all packages that
depend on them.
- Shared libraries can be used as dependencies to other shared
libraries (fPIC is enabled by default on SHARED libraries).
- Shared libraries result in smaller installs because the code from each
library is not copied into each binary.
The disadvantage of shared libraries is that the compiler is restricted
from making certain types of optimizations, such as inlining.
Note that these sorts of optimizations only apply to code that is
actually in …
=> Type of library is SHARED

CMakeLists.txt, include/rsl/parameter_validators.hpp, include/rsl/static_vector.hpp, package.xml, src/parameter_validators.cpp, tests/CMakeLists.txt, tests/parameter_validators.cpp
I integrated [this file](https://github.com/PickNikRobotics/generate_parameter_library/blob/main/parameter_traits/include/parameter_traits/validators.hpp) and made some changes to match RSL conventions. One big change was replacing `Result` with `tl::expected<void, std::string>` which I think better expresses out intent.
There are still some TODOs for writing more docs and tests but this is good enough to warrant a draft PR.
=> Add validators.hpp

tests/parameter_validators.cpp
This just got overlooked in #51
=> Add tests for `rsl::to_parameter_result_msg`

tests/CMakeLists.txt
Do we absolutely need version 0.11.0? Does 0.10.0 work as well? This prevents this package to be build for Humble on Ubuntu Focal (which should be [supported](https://docs.ros.org/en/humble/Installation/Alternatives/Ubuntu-Development-Setup.html#:~:text=Tier%203%3A%20Ubuntu%20Linux%20%2D%20Focal%20(20.04)%2064%2Dbit))
https://packages.ubuntu.com/source/focal/range-v3
```
--- stderr: rsl                         
CMake Error at tests/CMakeLists.txt:4 (find_package):
Could not find a configuration file for package "range-v3" that is
compatible with requested version "0.11.0".
The following configuration files were considered but not accepted:
/usr/lib/cmake/range-v3/range-v3-config.cmake, version: 0.10.0
/lib/cmake/range-v3/range-v3-config.cmake, version: 0.10.0
---
Failed   <<< rsl [4.65s, …
```
=> Change version of range-v3 to allow building on Ubuntu Focal

src/random.cpp, tests/random.cpp
I think this is a more expressive and readable alternative to the status quo. That `first` variable was never all that intuitive to me.
=> Implement `rsl::rng()` with `std::optional`

include/rsl/monad.hpp, include/rsl/parameter_validators.hpp, include/rsl/try.hpp, tests/monad.cpp, tests/parameter_validators.cpp
There are seemingly some places where the factory functions are needed but in most instances we don't need them so I'm erring on the side of using constructors which involve fewer layer of indirection to understand.
=> Use constructors over factory functions when possible

.devcontainer/Dockerfile
This should fix the CI failures around `sensor-msgs`.
=> Upgrade with new pkgs to fix issue with ROS

CMakeLists.txt, package.xml
This adds my latest learnings about why we need to set BUILD_SHARED_LIBS on for ROS packages. We are using the tooling built by the ROS 2 team here get this change in behavior. An explanation as to why this was done was added to the commit message.
=> Depend on ament_cmake_ros to default SHARED to ON

include/rsl/parameter_validators.hpp, tests/parameter_validators.cpp
=> Deprecate `rsl::lower_bounds` and `rsl::upper_bounds`

.github/workflows/ci.yaml
Closes #56 
Codecov fails when using Clang so I just disabled that particular bit of the matrix since codecov on multiple compilers doesn't seem like a useful thing to do.
=> Use Clang in CI

tests/CMakeLists.txt
Reduced allocations and improved performance
Section tracking is 10%-25% faster than in v3.3.0
Assertion handling is 5%-10% faster than in v3.3.0
Test case registration is 1%-2% faster than in v3.3.0
=> Update Catch2 to version 3.3.2

src/random.cpp
https://en.cppreference.com/w/cpp/numeric/random/random_device
This type is actually an `unsigned int` not an `int`.
=> Use correct type for seed values

.clang-tidy
Our worst offending functions have a score of 5 which is basically nothing. I picked 15 as our limit because that is what SonarCloud uses and it's a nice, low number that we ought to never exceed for a library of this scale.
=> Enable function cognitive complexity check

package.xml
Git is only needed to build the tests (because it's used to clone Catch2) so it's more accurate to call it a test dependency.
=> Mark git as a test dependency

docs/CMakeLists.txt
Skip building documentation in the case that Doxygen is not detected on the system.
=> Make doxygen a weak dependency

CMakeLists.txt, cmake/rsl-config.cmake, package.xml
This is an experiment to determine whether we can build ROS packages that don't use ament. As far as we can tell, Ament is not strictly necessary but rather exists to provide some conveniences related to installing Cmake projects. Because we know how to install libraries using vanilla CMake, we can write that code ourselves rather than add a new dependency.
=> Remove ament macros

include/rsl/parameter_validators.hpp, tests/parameter_validators.cpp
In preparing slides for my talk on generate_parameter_library I produced this error message:
```
what():  Invalid value set during initialization for parameter 'my_string': 
Parameter 'my_string' with the value place is not in the set {world, base, home}
```
I think this would be much clearer if all the values in the error are quoted. The value `place` is kind of just hidden there in the middle.
=> Quote values in error messages

include/rsl/strong_type.hpp, tests/CMakeLists.txt, tests/strong_type.cpp
Strong type aliases are a useful pattern but they require just enough boilerplate that you don't typically see codebases implement them and they're just small and non-specific enough that libraries don't provide them. This type aims to fill that gap so that we can actually use strong type aliases in our code.
Motivating example:
```cpp
using JointID = rsl::StrongType<std::uint64_t, struct JointIDTag>;
struct Joint {
JointID id;
int count;
};
auto joint = Joint{JointID(4), 2};
auto joint = Joint{2, JointID(4)}; // Won't compile
```
The presence of a strong type alias ensures that the order of arguments is correct. Without that strong alias, it would be easy to accidentally swap the two arguments without realizing it.
=> Add `rsl::StrongType`

include/rsl/random.hpp, include/rsl/static_string.hpp, include/rsl/static_vector.hpp
It's very user friendly to provide some explanation for why a compiletime or runtime assertion failed.
=> Add more messages for assertion failures

CMakeLists.txt, CMakePresets.json
Those who build RSL from source in their workspace do not need to build our tests. Let's disable them by default. The default build ought to be as minimal as possible as to prevent unnecessary build failures as seen in #103.
=> Disable tests by default

package.xml, tests/install/CMakeLists.txt
These tests should give us a lot more confidence for now and in the future that we maintain support with `ament_target_dependencies` users.
=> Test consuming RSL via `ament_target_dependencies`

CMakeLists.txt, CMakePresets.json
Unconditionally enabling `-Werror` is a heavy-handed approach and not ideal when shipping code to be used by many third parties. In fact it's even better to disable warnings by default since compiler warnings are not hard requirements. They're merely a development tool that developers should opt into.
Closes #117
=> Disable compiler warnings by default

tests/CMakeLists.txt
The `TRY` macro requires a GCC/Clang extension so we need to make sure we only compile those tests when GCC or Clang is being used.
Addresses part of but not all #116.
=> Disable `TRY` macro tests on MSVC

tests/static_string.cpp
`std::array`'s iterator is a pointer in libc++ and libstdc++ so `const auto*` works fine. However the array iterator is not a pointer on MSVC so compilation fails. Removing the asterisk still results in a pointer type being used but causes a clang-tidy check to fail so we have to disable that.
=> Fix static_string.cpp compilation with MSVC standard library

CMakeLists.txt, include/rsl/parameter_validators.hpp, include/rsl/random.hpp
https://gcc.gnu.org/wiki/Visibility
Hiding symbols by default from shared libraries has benefits you can read about above. Along with doing this we also ensure that DLLs are supported on Windows and thus make sure we provide 1st class support to all uses irrespective of their platform of choice.
=> Hide symbols from shared libraries by default and support DLL creation

CMakeLists.txt
=> Eigen: Add NO_MODULE to find_package
